# Generated by Django 5.0.2 on 2025-03-09 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('categorie', models.CharField(choices=[('CITADINE', 'Citadine'), ('BERLINE', 'Berline'), ('SUV', 'SUV'), ('UTILITAIRE', 'Utilitaire'), ('LUXE', 'Luxe')], max_length=20)),
                ('description', models.TextField()),
                ('prix_jour', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('disponible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicules/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-date_creation'],
            },
        ),
    ]
